### ISSUE TITLE
React Hook "useMemo" is called conditionally

### ISSUE THREAD

**Issue by dalle** [intergalacticspacehighway/use-reducer-thunk#40]
https://github.com/intergalacticspacehighway/use-reducer-thunk/blob/5d01e6feaf5b248256fbf65f50f852a6f139a333/src/index.js#L31

```js
  if (shouldConfigDevTools) {
    memoizedReducer = useMemo(() => devToolReducer(reducer), [reducer]);
  }
```

Running ESLint on the code I got the following error:

React Hook "useMemo" is called conditionally. React Hooks must be called in the exact same order in every component render. (react-hooks/rules-of-hooks)

**Comment by intergalacticspacehighway** [comment]
Fixed in version 1.1.0. Thanks to @mrclay!
