### ISSUE TITLE
action parameters

### ISSUE THREAD

**Issue by cmonacaps** [intergalacticspacehighway/use-reducer-thunk#5]
[The redux-thunk-middleware implementation](https://github.com/reduxjs/redux-thunk/blob/6cec3962d80853b48525a3eb99299c1cb7e4b10d/src/index.js#L1-L9) invokes `action(dispatch, getState, extraArgument)`, having used that a while now, the way I would write the thunks would be to use `getState` rather than trying to capture the state when creating the action, here's an example:

`<button text="add 5 points to your score" onClick={dispatch(createAddPointsAction(5))} />`

where
```js
const createAddPointsAction = delta =>
  async (dispatch, getState) => dispatch('SET_SCORE', getState().score + delta)
```

That's a bit contrived since you could just `dispatch('ADD_TO_SCORE', delta)` but there are a lot of situations for adjusting state during some multistep async operation, like wait on the response from a server and then adjust some existing value in state based on the response..

Anyhow there are several "use enhanced reducer" packages that are compatible with redux-thunk-middleware in this regard, but those do not have what looks like pretty good coordination with redux-devtools, was interested to give that a try..

**Comment by intergalacticspacehighway** [comment]
@cmonacaps this PR should resolve the issue. 
https://github.com/intergalacticspacehighway/use-reducer-thunk/pull/3/files

**Comment by cmonacaps** [comment]
thanks, will take a fresh look 👍
