### ISSUE TITLE
[QUESTION] Is it possible to use it in an App that already uses `redux` and `redux-dev-tools` ?

### ISSUE THREAD

**Issue by cbdeveloper** [intergalacticspacehighway/use-reducer-thunk#8]
I am already using regular `redux` together with `redux-devtools-extension` as a global state manager for my App.

I think I'm going to implement `useReducer` as a "nested store" for a specific section of my web App. And I would like to use `thunks` just like I do with `redux-thunk` middleware.

But since I'm already using regular `redux` and the `redux-devtools`, is it possible to use `use-reducer-thunk` under those conditions? 

Because I saw that this package also registers as a "store" for the `redux-devtools`.

How would the `devtools` work in this case?

Thanks

**Comment by intergalacticspacehighway** [comment]
@cbdeveloper Yeah it should work, use it like this useReducerWithThunk(reducer, initialState, name). Pass a name parameter. You'll see the listing of your useReducer store in Select instances dropdown in redux devtools.

**Comment by intergalacticspacehighway** [comment]
@cbdeveloper closing the issue. Let me know if you face any issues.
